version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo No build needed for PHP app
artifacts:
  files:
    - '**/*'
